# Generated by Django 2.1.1 on 2018-10-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlgenerator',
            name='anc',
        ),
    ]
