# Generated by Django 2.1.1 on 2018-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0002_remove_urlgenerator_anc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlgenerator',
            name='url',
            field=models.URLField(),
        ),
    ]
