# Generated by Django 2.1.1 on 2018-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0003_auto_20181002_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlgenerator',
            name='stoped',
        ),
        migrations.AddField(
            model_name='urlgenerator',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
