# Generated by Django 2.1.1 on 2018-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0004_auto_20181002_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlgeneratortask',
            name='links_number',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
