# Generated by Django 2.1.1 on 2018-10-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0005_urlgeneratortask_links_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='urlgeneratortask',
            name='errors',
        ),
        migrations.AlterField(
            model_name='urlgeneratortask',
            name='results',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='url_generator.ResultsUrl'),
            preserve_default=False,
        ),
    ]
