# Generated by Django 2.1.1 on 2018-10-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0006_auto_20181002_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorsUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='urlgeneratortask',
            name='errors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='url_generator.ErrorsUrl'),
            preserve_default=False,
        ),
    ]
