# Generated by Django 2.1.1 on 2018-10-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0007_auto_20181002_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlgeneratortask',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='urlgeneratortask',
            name='results',
        ),
        migrations.DeleteModel(
            name='ErrorsUrl',
        ),
        migrations.DeleteModel(
            name='ResultsUrl',
        ),
    ]
