# Generated by Django 2.1.1 on 2018-10-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0008_auto_20181002_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlgeneratortask',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlgenerator',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
