# Generated by Django 2.1.1 on 2018-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0009_auto_20181002_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlgeneratortask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='prg1/'),
        ),
        migrations.AlterField(
            model_name='urlgeneratortask',
            name='desc_variations',
            field=models.PositiveSmallIntegerField(blank=True, default='1', help_text='Введите жалаемое число создаваемых вариаций анкора', null=True, verbose_name='Число создаваемых вариаций анкора'),
        ),
        migrations.AlterField(
            model_name='urlgeneratortask',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Вариативный анкор []-перемешать {}-выбрать'),
        ),
        migrations.AlterField(
            model_name='urlgeneratortask',
            name='youtube_url',
            field=models.CharField(max_length=128, verbose_name='YouTube URL (!Not youtu.be !)'),
        ),
    ]
