# Generated by Django 2.1.1 on 2018-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0010_auto_20181004_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_file', models.FileField(upload_to='')),
            ],
        ),
    ]
