# Generated by Django 2.1.1 on 2019-01-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0012_auto_20181008_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadfiledata',
            name='load_file',
        ),
        migrations.DeleteModel(
            name='LoadFile',
        ),
        migrations.DeleteModel(
            name='LoadFileData',
        ),
    ]
