# Generated by Django 2.1.1 on 2019-01-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0013_auto_20190106_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlgeneratortask',
            name='file',
        ),
    ]
