# Generated by Django 2.1.1 on 2019-01-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0015_auto_20190106_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlgenerator',
            name='date_inactive',
        ),
    ]
