# Generated by Django 2.1.1 on 2019-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0016_remove_urlgenerator_date_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlgenerator',
            name='date_inactive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
