# Generated by Django 2.1.1 on 2019-01-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0018_auto_20190113_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StopDomains',
            new_name='StopDomain',
        ),
    ]
