# Generated by Django 2.1.1 on 2019-01-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0020_auto_20190113_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=11, verbose_name='Youtube key')),
                ('slug', models.CharField(max_length=11, verbose_name='slug')),
            ],
        ),
        migrations.AddField(
            model_name='searchurlstack',
            name='checked_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchurlstack',
            name='checked_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchurlstack',
            name='key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='url_generator.SearchStack'),
        ),
    ]
