# Generated by Django 2.1.1 on 2019-01-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0021_auto_20190113_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchurlstack',
            name='url',
            field=models.CharField(max_length=512, verbose_name='URL'),
        ),
    ]
