# Generated by Django 2.1.1 on 2019-01-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0022_auto_20190113_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchstack',
            name='slug',
            field=models.CharField(max_length=256, verbose_name='slug'),
        ),
    ]
