# Generated by Django 2.1.1 on 2019-01-13 15:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0023_auto_20190113_1729'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='searchstack',
            managers=[
                ('keys', django.db.models.manager.Manager()),
            ],
        ),
    ]
