# Generated by Django 2.1.1 on 2019-01-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0026_searchurlstack_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchurlstack',
            name='attempt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
