# Generated by Django 2.1.1 on 2019-01-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0028_stopdomain_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopdomain',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Bane reason or error'),
        ),
    ]
