# Generated by Django 2.1.1 on 2019-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0029_stopdomain_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchstack',
            name='slug',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='slug'),
        ),
    ]
