# Generated by Django 2.1.1 on 2019-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0031_searchstack_s2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchstack',
            name='s2',
        ),
        migrations.AddField(
            model_name='searchstack',
            name='slug_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='slug_2'),
        ),
    ]
