# Generated by Django 2.1.1 on 2019-01-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0032_auto_20190120_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstack',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
