# Generated by Django 2.1.1 on 2019-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0033_searchstack_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchstack',
            name='slug_2',
        ),
        migrations.AddField(
            model_name='searchstack',
            name='processed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='searchstack',
            name='slug_uni',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='slug_unicode_safe'),
        ),
    ]
