# Generated by Django 2.1.1 on 2019-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0034_auto_20190120_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchstack',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
