# Generated by Django 2.1.1 on 2019-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_generator', '0035_auto_20190120_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstack',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Youtube desc'),
        ),
    ]
